### ISSUE TITLE
Corpus from running text view

### ISSUE THREAD

**Issue by kchall** [kchall/CorpusTools#240]
It's still the case that a corpus from running text (e.g. the Gitksan one) shows up with only partial words visible in the running text view (see attached image). (Also, is it possible to make the running text view optional?)
![partial_running_text_view](https://cloud.githubusercontent.com/assets/7317450/5734429/03f00ac0-9b6a-11e4-8957-c471c4aae287.jpg)

**Comment by kchall** [comment]
Hmm, this didn't automatically fix a pre-existing corpus when I got the latest commit. But then when I tried to re-create the corpus from running text, I got the following error:

Traceback (most recent call last):
File "/Users/kchall/Desktop/CorpusTools/corpustools/gui/qt/corpusgui.py", line 81, in run
corpus = load_transcription_corpus(**self.kwargs)
File "/Users/kchall/Desktop/CorpusTools/corpustools/corpus/io/text_transcription.py", line 100, in load_transcription_corpus
trans_patt = '['+patt+']+'
NameError: name 'patt' is not defined

**Comment by mmcauliffe** [comment]
Whoops, try the latest commit on master now.  It shouldn't fix the old corpora generated under previous versions of it (since I still have no idea how they got the way that they did), but newly generated should be working.

**Comment by kchall** [comment]
Well, you're right that I can now generate the corpus again, but the partial-word view is still an issue:
![partial_running_text_view_2](https://cloud.githubusercontent.com/assets/7317450/5811173/64499354-a007-11e4-83d6-ae80301161b8.jpg)

**Comment by mmcauliffe** [comment]
Huh, must be a mac issue.  I'll check into it tomorrow.
